services:
  - type: web
    name: epilepsia-cdss-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    envVars:
      - key: DROOLS_JAR
        value: /app/drools-engine.jar
      - key: OWL_PATH
        value: /app/clase_temporal.rdf
